#!/bin/bash

##BEGIN#________________________>#_|FUNCTION|_#<______________________________##

function	utils::mkdir()
{
	local	dir_path="${1:-}"

	[ -f "${dir_path}" ] && rm -f "${dir_path}"
	[ -d "${dir_path}" ] && rm -rf "${dir_path}"
	[ ! -d "${dir_path}" ] && mkdir -p "${dir_path}"
}

function	jail::copy_library()
{
	declare	-a	library
	local		base_dir

	library=($(\
	for command_path in $(find "${JAIL_PATH}/bin" -type f -executable -print); do
		ldd "${command_path}" | perl -ne "print if s|^.*?(/lib.*?) .*$|\1|g"
	done | sort -u))

	for element in ${library[@]}; do
		base_dir="${JAIL_PATH}${element%\/*}"
		mkdir -p "${base_dir}"
		cp "${element}" "${base_dir}"
	done
}

function	jail::copy_command()
{
	local	command_path

	for command in "${ALLOWED_CMD[@]}"; do
		command_path=$(type -P "${command}")
		[ "${command_path}" ] && cp "${command_path}" "${JAIL_PATH}/bin"
	done
}

function	jail::mkdir()
{
	utils::mkdir "${JAIL_PATH}/bin"
	utils::mkdir "${JAIL_PATH}/etc"
	utils::mkdir "${JAIL_PATH}/lib"
	utils::mkdir "${JAIL_PATH}/lib64"
	utils::mkdir "${JAIL_PATH}/home"
}

function	jail::configure_bash()
{
	local	c_r=$(printf '%b' '\x1b[31m')
	local	c_y=$(printf '%b' '\x1b[33m')
	local	c_g=$(printf '%b' '\x1b[32m')
	local	c_u=$(printf '%b' '\x1b[4m')
	local	rst=$(printf '%b' '\x1b[0m')

	prompt="${c_r}${USER}"
	prompt+="🔒"
	prompt+="${c_y}\\h${rst}"
	prompt+=" [ ${c_g}${c_u}\\w${rst} ] $ "

	echo "PS1=\"${prompt}\"" > "${JAIL_PATH}/etc/bash.bashrc"
	cp -r /lib/terminfo "${JAIL_PATH}/etc/"
}

function	jail::prepare()
{
	jail::mkdir
	jail::copy_command
	jail::copy_library
	jail::configure_bash
}

function	jail::clean()
{
	[ -d "${JAIL_PATH}" ] && rm -rf "${JAIL_PATH}"
	trap - SIGINT SIGQUIT SIGTSTP
	exit 1
}

function	jail::entry()
{
	jail::prepare
	(exec \
		unshare \
			--map-user=$(id -ru) \
			--map-group=$(id -rg) \
			--pid \
			--kill-child=SIGQUIT \
			bwrap \
				--bind "${JAIL_PATH}" / \
				--dev-bind "${BASE_HOME}" "/home/${USER}" \
				--unshare-all \
				--chdir "${BASE_HOME}" \
				--clearenv \
				--setenv PROMPT_DIRTRIM "2" \
				--setenv LS_COLORS "${LS_COLORS}" \
				--setenv TERM "${TERM}" \
				--hostname jailed \
				"/bin/bash")
	jail::clean
}

##END#__________________________<#_|FUNCTION|_#>______________________________##

##BEGIN#__________________________>#_|MAIN|_#<________________________________##

trap "jail::clean" SIGINT SIGQUIT SIGTSTP

BASE_HOME=/home
BASE_HOME="${BASE_HOME}/${USER}"
JAIL_PATH="${BASE_HOME}/.jail"

ALLOWED_CMD=(
	"bash"
	"cat"
	"du"
	"less"
	"ls"
	"rm"
	"clear"
)

jail::entry

##END#____________________________<#_|MAIN|_#>________________________________##

